[package]
authors = ["steinuil <steenuil.owl@gmail.com>"]
edition = "2018"
name = "coof"
version = "0.1.0"

[dependencies]
clap = "2.33"
log = "0.4"
reqwest = "0.11"
serde_json = "1.0"
simple_logger = "1.13"
structopt = "0.3"
tokio = {version = "1.12", features = ["full"]}
