[package]
authors = ["steinuil <steenuil.owl@gmail.com>"]
edition = "2018"
name = "coof"
version = "0.1.0"

[dependencies]
futures = "0.3"
mio = {version = "0.7", features = ["os-ext"]}
miow = "0.3"
reqwest = "0.10"
serde_json = "1.0"
tokio = {version = "0.2", features = ["full"]}
